#!/usr/bin/env bash
# Запуск Hadoop-сервиса в зависимости от $HADOOP_ROLE.
# Поддерживаемые роли:
#   namenode | secondarynamenode | datanode |
#   resourcemanager | nodemanager | historyserver |
#   worker  (DataNode + NodeManager в одном контейнере, для local-compose)
set -euo pipefail

ROLE="${HADOOP_ROLE:-}"
if [[ -z "$ROLE" ]]; then
    echo "[entrypoint] HADOOP_ROLE не задан. Допустимые значения:"
    echo "             namenode, secondarynamenode, datanode,"
    echo "             resourcemanager, nodemanager, historyserver"
    exit 1
fi

# JAVA_HOME уже выставлен базовым образом eclipse-temurin, но подстрахуемся.
if [[ -z "${JAVA_HOME:-}" && -d /opt/java/openjdk ]]; then
    export JAVA_HOME=/opt/java/openjdk
fi

mkdir -p "${HADOOP_DATA_DIR}/namenode" \
         "${HADOOP_DATA_DIR}/datanode" \
         "${HADOOP_DATA_DIR}/secondary" \
         "${HADOOP_DATA_DIR}/tmp" \
         "${HADOOP_LOG_DIR}"

# Ждём, пока удалённый сервис начнёт принимать соединения.
wait_for() {
    local host="$1" port="$2"
    local timeout="${3:-180}"
    local waited=0
    echo "[entrypoint] жду ${host}:${port} (таймаут ${timeout}s)..."
    while ! nc -z "${host}" "${port}" 2>/dev/null; do
        sleep 2
        waited=$((waited + 2))
        if (( waited >= timeout )); then
            echo "[entrypoint] таймаут ожидания ${host}:${port}" >&2
            return 1
        fi
    done
    echo "[entrypoint] ${host}:${port} доступен"
}

NAMENODE_HOST="${NAMENODE_HOST:-namenode}"
RESOURCEMANAGER_HOST="${RESOURCEMANAGER_HOST:-resourcemanager}"

# In multi-host Docker setups, /etc/hosts contains TWO entries for the
# container's hostname:
#   192.168.1.11  worker1        ← from extra_hosts (LAN IP, correct)
#   172.18.0.3    <id> worker1   ← auto-generated by Docker (bridge IP)
#
# Java's InetAddress.getLocalHost() may pick the bridge IP, causing the
# DataNode and similar services to advertise an address unreachable
# from other hosts. This function removes the bridge IP entry so only
# the LAN IP remains. In single-host (local) compose there are no
# extra_hosts, so the function is a no-op.
fix_hostname_for_lan() {
    local hn
    hn="$(hostname)"
    local count
    count=$(grep -c "\b${hn}\b" /etc/hosts 2>/dev/null || echo 0)
    if [ "$count" -ge 2 ]; then
        # Cannot use sed -i on /etc/hosts: Docker bind-mounts it, so rename
        # (which sed -i uses internally) fails with "Device or resource busy".
        # Instead, filter into a temp file and write back via cat > (in-place).
        local tmpf
        tmpf=$(mktemp)
        grep -v "^172\..*\b${hn}\b" /etc/hosts > "$tmpf"
        cat "$tmpf" > /etc/hosts
        rm -f "$tmpf"
        echo "[entrypoint] /etc/hosts: removed bridge IP for ${hn}, keeping LAN IP only"
    fi
}

# The opposite of fix_hostname_for_lan: ensure the container's own hostname
# resolves to a LOCAL interface (the docker bridge IP) so that Spark/YARN
# executor processes spawned inside this container can bind their Netty
# services. YARN passes --hostname <NODE_NAME> to the executor; Spark's
# NettyBlockTransferService then binds to InetAddress.getByName(<NODE_NAME>).
# Without this fix, <NODE_NAME> resolves to the LAN IP (via extra_hosts),
# which is not assigned to any interface inside the container, and bind()
# fails with "Cannot assign requested address" (EADDRNOTAVAIL). Other hosts
# still resolve <NODE_NAME> to the LAN IP through their own extra_hosts, so
# cross-host RPC is unaffected.
#
# NOTE: must be safe under `set -euo pipefail`. We use only tools guaranteed
# to exist in the base image (`hostname`, `awk`, `getent`, `grep`, `cat`,
# `mktemp`) and guard every pipeline with `|| true` so a transient failure
# never crashes the entrypoint — the worst case is we log a warning and
# leave /etc/hosts as-is.
ensure_local_hostname_bindable() {
    local hn bridge_ip first_ip tmpf
    hn="$(hostname)"
    # `hostname -I` (from the `hostname` package on jammy) prints all
    # non-loopback IPv4/IPv6 addresses assigned to the container, separated
    # by spaces. The first one is the docker bridge IP. `iproute2` (`ip`)
    # is NOT in the base image, so we rely on this.
    bridge_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    if [[ -z "$bridge_ip" ]]; then
        # Fallback: pick the first IPv4 address out of `getent ahosts <hn>`
        # that is NOT one of the addresses Docker put in via extra_hosts.
        # Even this is best-effort; if it fails we just bail.
        bridge_ip="$(getent ahosts "${hn}" 2>/dev/null \
                     | awk '/STREAM/ {print $1}' \
                     | grep -v '^192\.\|^10\.\|^127\.' \
                     | head -n1 || true)"
    fi
    if [[ -z "$bridge_ip" ]]; then
        echo "[entrypoint] WARN: не удалось определить bridge IP для ${hn};" \
             "Spark executor может упасть с BindException: Cannot assign requested address" >&2
        return 0
    fi
    # If the bridge IP is already what ${hn} resolves to first, nothing to do.
    first_ip="$(getent hosts "${hn}" 2>/dev/null | awk 'NR==1 {print $1}' || true)"
    if [[ "$first_ip" == "$bridge_ip" ]]; then
        return 0
    fi
    tmpf="$(mktemp)"
    {
        printf '%s\t%s\n' "$bridge_ip" "$hn"
        cat /etc/hosts
    } > "$tmpf"
    cat "$tmpf" > /etc/hosts
    rm -f "$tmpf"
    echo "[entrypoint] /etc/hosts: ${hn} -> ${bridge_ip} (локальный bridge IP)" \
         "для Spark executor bind; LAN IP остаётся в /etc/hosts"
}

# DataNode'ы на разных воркерах НЕ должны иметь одинаковый xferPort,
# когда они идут к NameNode через NAT мастер-ноута: иначе NameNode видит
# у обоих source-IP мастер-bridge gateway (например 172.18.0.1) и тот же
# порт 9866, и считает их одним и тем же узлом, выкидывая друг друга
# по очереди. Поэтому DN на workerN получает xferPort 9866 + (N-1)*10.
compute_dn_port_offset() {
    local name="${1:-worker1}"
    case "$name" in
        worker[0-9]|worker[0-9][0-9])
            local num="${name#worker}"
            echo $(( (num - 1) * 10 ))
            ;;
        *)
            echo 0
            ;;
    esac
}

# Hadoop Configuration НЕ читает JVM system-properties (-D перед main-классом),
# а только XML из HADOOP_CONF_DIR + аргумент -conf. Поэтому per-DN-настройки
# (адреса/порты + hostname) дописываем напрямую в hdfs-site.xml перед стартом.
inject_dn_overrides() {
    local node_name="$1" xfer="$2" http="$3" ipc="$4"
    local cfg="${HADOOP_CONF_DIR}/hdfs-site.xml"
    python3 - "$cfg" "$node_name" "$xfer" "$http" "$ipc" <<'PY'
import sys, xml.etree.ElementTree as ET
cfg, node, xfer, http, ipc = sys.argv[1:6]
tree = ET.parse(cfg)
root = tree.getroot()
overrides = {
    "dfs.datanode.address": f"0.0.0.0:{xfer}",
    "dfs.datanode.http.address": f"0.0.0.0:{http}",
    "dfs.datanode.ipc.address": f"0.0.0.0:{ipc}",
    "dfs.datanode.hostname": node,
}
existing = {p.find("name").text: p for p in root.findall("property")
            if p.find("name") is not None}
for name, value in overrides.items():
    prop = existing.get(name)
    if prop is None:
        prop = ET.SubElement(root, "property")
        ET.SubElement(prop, "name").text = name
        ET.SubElement(prop, "value").text = value
    else:
        v = prop.find("value")
        if v is None:
            v = ET.SubElement(prop, "value")
        v.text = value
tree.write(cfg, encoding="UTF-8", xml_declaration=True)
PY
}

case "$ROLE" in
    namenode)
        if [[ ! -f "${HADOOP_DATA_DIR}/namenode/current/VERSION" ]]; then
            echo "[entrypoint] форматирую NameNode (первый запуск)"
            hdfs namenode -format -nonInteractive -force \
                -clusterId "${HADOOP_CLUSTER_ID:-clustrer-hadoop}"
        fi
        exec hdfs namenode
        ;;

    secondarynamenode)
        wait_for "${NAMENODE_HOST}" 9000
        exec hdfs secondarynamenode
        ;;

    datanode)
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для datanode}"
        fix_hostname_for_lan
        wait_for "${NAMENODE_HOST}" 9000
        # Если порты заданы явно в .env — используем их, иначе считаем
        # из NODE_NAME (worker1 → 9866, worker2 → 9876, ...).
        DN_OFFSET="$(compute_dn_port_offset "${NODE_NAME}")"
        DN_HTTP_PORT="${DN_HTTP_PORT:-$((9864 + DN_OFFSET))}"
        DN_XFER_PORT="${DN_XFER_PORT:-$((9866 + DN_OFFSET))}"
        DN_IPC_PORT="${DN_IPC_PORT:-$((9867 + DN_OFFSET))}"
        echo "[entrypoint] DN ports: http=${DN_HTTP_PORT} xfer=${DN_XFER_PORT} ipc=${DN_IPC_PORT}"
        inject_dn_overrides "${NODE_NAME}" "${DN_XFER_PORT}" "${DN_HTTP_PORT}" "${DN_IPC_PORT}"
        exec hdfs datanode
        ;;

    resourcemanager)
        exec yarn resourcemanager
        ;;

    nodemanager)
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для nodemanager}"
        # NodeManager сам анонсируется через -Dyarn.nodemanager.hostname=${NODE_NAME}
        # (строкой, а не IP), поэтому НЕ зовём fix_hostname_for_lan: нам нужно,
        # чтобы внутри контейнера ${NODE_NAME} резолвился в локальный bridge IP
        # — иначе Spark-экзекьюторы, запущенные YARN'ом с --hostname ${NODE_NAME},
        # падают на NettyBlockTransferService.bind() с EADDRNOTAVAIL.
        ensure_local_hostname_bindable
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        export YARN_NODEMANAGER_OPTS="-Dyarn.nodemanager.hostname=${NODE_NAME} ${YARN_NODEMANAGER_OPTS:-}"
        exec yarn nodemanager
        ;;

    historyserver)
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        exec mapred historyserver
        ;;

    worker)
        # Один контейнер на worker'а несёт DataNode + NodeManager.
        # Уникальный NODE_NAME даёт разные hostname'ы worker1/worker2,
        # чтобы они не сталкивались на одной bridge-сети (актуально
        # для all-in-one-режима, когда несколько воркеров поднимаются
        # на одной машине).
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для worker}"
        # Spark-экзекьютор внутри NodeManager должен биндиться на локальный
        # интерфейс — см. комментарий в ensure_local_hostname_bindable().
        ensure_local_hostname_bindable
        wait_for "${NAMENODE_HOST}" 9000
        DN_OFFSET="$(compute_dn_port_offset "${NODE_NAME}")"
        DN_HTTP_PORT=$((9864 + DN_OFFSET))
        DN_XFER_PORT=$((9866 + DN_OFFSET))
        DN_IPC_PORT=$((9867 + DN_OFFSET))
        echo "[entrypoint] DN ports: http=${DN_HTTP_PORT} xfer=${DN_XFER_PORT} ipc=${DN_IPC_PORT}"
        inject_dn_overrides "${NODE_NAME}" "${DN_XFER_PORT}" "${DN_HTTP_PORT}" "${DN_IPC_PORT}"
        echo "[entrypoint] стартую DataNode в фоне"
        hdfs --daemon start datanode
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        export YARN_NODEMANAGER_OPTS="-Dyarn.nodemanager.hostname=${NODE_NAME} ${YARN_NODEMANAGER_OPTS:-}"
        echo "[entrypoint] стартую NodeManager (foreground)"
        exec yarn nodemanager
        ;;

    *)
        echo "[entrypoint] неизвестная роль: $ROLE" >&2
        exit 1
        ;;
esac
