#!/usr/bin/env bash
# Запуск Hadoop-сервиса в зависимости от $HADOOP_ROLE.
# Поддерживаемые роли:
#   namenode | secondarynamenode | datanode |
#   resourcemanager | nodemanager | historyserver |
#   worker  (DataNode + NodeManager в одном контейнере, для local-compose)
set -euo pipefail

ROLE="${HADOOP_ROLE:-}"
if [[ -z "$ROLE" ]]; then
    echo "[entrypoint] HADOOP_ROLE не задан. Допустимые значения:"
    echo "             namenode, secondarynamenode, datanode,"
    echo "             resourcemanager, nodemanager, historyserver"
    exit 1
fi

# JAVA_HOME уже выставлен базовым образом eclipse-temurin, но подстрахуемся.
if [[ -z "${JAVA_HOME:-}" && -d /opt/java/openjdk ]]; then
    export JAVA_HOME=/opt/java/openjdk
fi

mkdir -p "${HADOOP_DATA_DIR}/namenode" \
         "${HADOOP_DATA_DIR}/datanode" \
         "${HADOOP_DATA_DIR}/secondary" \
         "${HADOOP_DATA_DIR}/tmp" \
         "${HADOOP_LOG_DIR}"

# Ждём, пока удалённый сервис начнёт принимать соединения.
wait_for() {
    local host="$1" port="$2"
    local timeout="${3:-180}"
    local waited=0
    echo "[entrypoint] жду ${host}:${port} (таймаут ${timeout}s)..."
    while ! nc -z "${host}" "${port}" 2>/dev/null; do
        sleep 2
        waited=$((waited + 2))
        if (( waited >= timeout )); then
            echo "[entrypoint] таймаут ожидания ${host}:${port}" >&2
            return 1
        fi
    done
    echo "[entrypoint] ${host}:${port} доступен"
}

NAMENODE_HOST="${NAMENODE_HOST:-namenode}"
RESOURCEMANAGER_HOST="${RESOURCEMANAGER_HOST:-resourcemanager}"

# In multi-host Docker setups, /etc/hosts contains TWO entries for the
# container's hostname:
#   172.18.0.3    <id> worker1   ← auto-generated by Docker (bridge IP)
#   192.168.1.11  worker1        ← from extra_hosts (LAN IP)
#
# Java's InetAddress.getLocalHost() picks the FIRST match (bridge IP).
# That used to cause MRAppMaster / DataNode to advertise the bridge IP
# to peers on other hosts, who couldn't route to it. We fixed that with
# explicit `dfs.datanode.hostname=$NODE_NAME` and
# `yarn.nodemanager.hostname=$NODE_NAME` overrides (see datanode/nodemanager
# roles below), so Hadoop services now advertise the hostname instead of
# the auto-detected IP — fix_hostname_for_lan is no longer needed for them.
#
# However, Spark client-mode driver running in the resourcemanager
# container has no equivalent hostname override and uses getLocalHost()
# to advertise itself to executors. So we still call fix_hostname_for_lan
# in the resourcemanager role to ensure the bridge IP is removed there.
# On worker containers we leave both entries, so:
#   * Spark executor binds on bridge IP (locally bound — succeeds),
#   * but advertises hostname `worker1`, which the driver and peer workers
#     resolve to LAN IP via extra_hosts — cross-host comms work.
fix_hostname_for_lan() {
    local hn
    hn="$(hostname)"
    local count
    count=$(grep -c "\b${hn}\b" /etc/hosts 2>/dev/null || echo 0)
    if [ "$count" -ge 2 ]; then
        # Cannot use sed -i on /etc/hosts: Docker bind-mounts it, so rename
        # (which sed -i uses internally) fails with "Device or resource busy".
        # Instead, filter into a temp file and write back via cat > (in-place).
        local tmpf
        tmpf=$(mktemp)
        grep -v "^172\..*\b${hn}\b" /etc/hosts > "$tmpf"
        cat "$tmpf" > /etc/hosts
        rm -f "$tmpf"
        echo "[entrypoint] /etc/hosts: removed bridge IP for ${hn}, keeping LAN IP only"
    fi
}

# DataNode'ы на разных воркерах НЕ должны иметь одинаковый xferPort,
# когда они идут к NameNode через NAT мастер-ноута: иначе NameNode видит
# у обоих source-IP мастер-bridge gateway (например 172.18.0.1) и тот же
# порт 9866, и считает их одним и тем же узлом, выкидывая друг друга
# по очереди. Поэтому DN на workerN получает xferPort 9866 + (N-1)*10.
compute_dn_port_offset() {
    local name="${1:-worker1}"
    case "$name" in
        worker[0-9]|worker[0-9][0-9])
            local num="${name#worker}"
            echo $(( (num - 1) * 10 ))
            ;;
        *)
            echo 0
            ;;
    esac
}

# Hadoop Configuration НЕ читает JVM system-properties (-D перед main-классом),
# а только XML из HADOOP_CONF_DIR + аргумент -conf. Поэтому per-DN-настройки
# (адреса/порты + hostname) дописываем напрямую в hdfs-site.xml перед стартом.
inject_dn_overrides() {
    local node_name="$1" xfer="$2" http="$3" ipc="$4"
    local cfg="${HADOOP_CONF_DIR}/hdfs-site.xml"
    python3 - "$cfg" "$node_name" "$xfer" "$http" "$ipc" <<'PY'
import sys, xml.etree.ElementTree as ET
cfg, node, xfer, http, ipc = sys.argv[1:6]
tree = ET.parse(cfg)
root = tree.getroot()
overrides = {
    "dfs.datanode.address": f"0.0.0.0:{xfer}",
    "dfs.datanode.http.address": f"0.0.0.0:{http}",
    "dfs.datanode.ipc.address": f"0.0.0.0:{ipc}",
    "dfs.datanode.hostname": node,
}
existing = {p.find("name").text: p for p in root.findall("property")
            if p.find("name") is not None}
for name, value in overrides.items():
    prop = existing.get(name)
    if prop is None:
        prop = ET.SubElement(root, "property")
        ET.SubElement(prop, "name").text = name
        ET.SubElement(prop, "value").text = value
    else:
        v = prop.find("value")
        if v is None:
            v = ET.SubElement(prop, "value")
        v.text = value
tree.write(cfg, encoding="UTF-8", xml_declaration=True)
PY
}

case "$ROLE" in
    namenode)
        if [[ ! -f "${HADOOP_DATA_DIR}/namenode/current/VERSION" ]]; then
            echo "[entrypoint] форматирую NameNode (первый запуск)"
            hdfs namenode -format -nonInteractive -force \
                -clusterId "${HADOOP_CLUSTER_ID:-clustrer-hadoop}"
        fi
        exec hdfs namenode
        ;;

    secondarynamenode)
        wait_for "${NAMENODE_HOST}" 9000
        exec hdfs secondarynamenode
        ;;

    datanode)
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для datanode}"
        # Чистить /etc/hosts не нужно: dfs.datanode.hostname ниже выставляется
        # хостнейм явно, а bind-IP оставляем таким, как его выберет Java
        # (bridge IP) — он точно привязан к интерфейсу. Это важно для Spark:
        # executor его BlockManager пытается забиндиться на тот же IP, что
        # резолвится из hostname, и без bridge IP в /etc/hosts падает с
        # BindException на LAN IP, не привязанном к интерфейсу контейнера.
        wait_for "${NAMENODE_HOST}" 9000
        # Если порты заданы явно в .env — используем их, иначе считаем
        # из NODE_NAME (worker1 → 9866, worker2 → 9876, ...).
        DN_OFFSET="$(compute_dn_port_offset "${NODE_NAME}")"
        DN_HTTP_PORT="${DN_HTTP_PORT:-$((9864 + DN_OFFSET))}"
        DN_XFER_PORT="${DN_XFER_PORT:-$((9866 + DN_OFFSET))}"
        DN_IPC_PORT="${DN_IPC_PORT:-$((9867 + DN_OFFSET))}"
        echo "[entrypoint] DN ports: http=${DN_HTTP_PORT} xfer=${DN_XFER_PORT} ipc=${DN_IPC_PORT}"
        inject_dn_overrides "${NODE_NAME}" "${DN_XFER_PORT}" "${DN_HTTP_PORT}" "${DN_IPC_PORT}"
        exec hdfs datanode
        ;;

    resourcemanager)
        # /etc/hosts в multi-host сетапе содержит две строки для
        # `resourcemanager`: bridge-IP от Docker и LAN-IP из extra_hosts.
        # Сносим bridge-строку, чтобы Java/Spark видели ровно LAN-IP
        # (иначе Spark-драйвер в client-mode рекламирует воркерам
        # bridge-IP 172.18.0.x, который с других машин не достижим).
        fix_hostname_for_lan
        exec yarn resourcemanager
        ;;

    nodemanager)
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для nodemanager}"
        # /etc/hosts не трогаем по тем же причинам, что и в datanode:
        # yarn.nodemanager.hostname явно рекламирует hostname в RM,
        # а bind-host=0.0.0.0 и hostname=bridge_IP делают возможным
        # bind для Spark BlockManager-а executor-а.
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        export YARN_NODEMANAGER_OPTS="-Dyarn.nodemanager.hostname=${NODE_NAME} ${YARN_NODEMANAGER_OPTS:-}"
        exec yarn nodemanager
        ;;

    historyserver)
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        exec mapred historyserver
        ;;

    worker)
        # Один контейнер на worker'а несёт DataNode + NodeManager.
        # Уникальный NODE_NAME даёт разные hostname'ы worker1/worker2,
        # чтобы они не сталкивались на одной bridge-сети (актуально
        # для all-in-one-режима, когда несколько воркеров поднимаются
        # на одной машине).
        : "${NODE_NAME:?NODE_NAME (worker1|worker2|...) обязателен для worker}"
        wait_for "${NAMENODE_HOST}" 9000
        DN_OFFSET="$(compute_dn_port_offset "${NODE_NAME}")"
        DN_HTTP_PORT=$((9864 + DN_OFFSET))
        DN_XFER_PORT=$((9866 + DN_OFFSET))
        DN_IPC_PORT=$((9867 + DN_OFFSET))
        echo "[entrypoint] DN ports: http=${DN_HTTP_PORT} xfer=${DN_XFER_PORT} ipc=${DN_IPC_PORT}"
        inject_dn_overrides "${NODE_NAME}" "${DN_XFER_PORT}" "${DN_HTTP_PORT}" "${DN_IPC_PORT}"
        echo "[entrypoint] стартую DataNode в фоне"
        hdfs --daemon start datanode
        wait_for "${RESOURCEMANAGER_HOST}" 8032
        export YARN_NODEMANAGER_OPTS="-Dyarn.nodemanager.hostname=${NODE_NAME} ${YARN_NODEMANAGER_OPTS:-}"
        echo "[entrypoint] стартую NodeManager (foreground)"
        exec yarn nodemanager
        ;;

    *)
        echo "[entrypoint] неизвестная роль: $ROLE" >&2
        exit 1
        ;;
esac
